hometask 7
ilya-pchelintsev/ml-course pull request #7
Opened 2019-11-30 09:54 UTC by ilya-pchelintsev

2019-11-30 13:50 UTC, illarionovEA requested changes
в лекции была опечатка: при вычислении ```p_k``` вычитаются не 1, а индикаторы того, что i-ый токен был отнесен к топику k, этот момент в лекции поправил

в тоей раелизации при вычислении ```р``` совсем ничего не нужно вычитать, так как это уже сделано в строках выше при обновлении счетчиков

2019-11-30 14:00 UTC, illarionovEA commented
вектор beta имеет размерность словаря, а не числа топиков

2019-11-30 14:22 UTC, illarionovEA commented
результат не обновился?

2019-12-06 15:50 UTC, illarionovEA approved these changes

2019-12-06 15:52 UTC, illarionovEA commented
предлагаю подумать, как сделать результат более интересным

2019-12-06 21:05 UTC, ilya-pchelintsev commented
Я уменьшил размер словаря. Убрал слова, которые встречались очень редко и очень часто. Частые слова выделялись в отдельный топик, который присутствовал во всех документах с высокой вероятностью и мешал выделять существенные темы. Редкие слова вносили лишь шум и замедляли время работы. Сокращение словаря позволило сделать больше итераций.

Темы выделились достаточно четко.

2019-12-06 21:10 UTC, merged

2019-12-06 21:36 UTC, illarionovEA commented
Отлично! Добавь, пожалуйста, в группе в комментариях к лекции твое предложение по уменьшению словаря